export interface Video {
  id: string;
  title: string;
  channel: string;
  channelAvatar: string;
  thumbnail: string;
  views: string;
  uploadedAt: string;
  duration: string;
  verified: boolean;
  subscribers?: string;
  description?: string;
  tags?: string[];
  likes?: string;
}

export const CATEGORIES = [
  'All', 'Gaming', 'Music', 'Live', 'Podcasts', 'Coding',
  'Science', 'Travel', 'Sports', 'News', 'Fashion', 'Cooking',
  'Comedy', 'Education', 'Technology', 'Fitness',
];

export const VIDEOS: Video[] = [
  {
    id: '1',
    title: 'Building a Full-Stack App with Next.js 14 & TypeScript – Complete Tutorial',
    channel: 'CodeWithMe',
    channelAvatar: 'https://i.pravatar.cc/40?img=1',
    thumbnail: 'https://picsum.photos/seed/code1/640/360',
    views: '2.3M',
    uploadedAt: '3 weeks ago',
    duration: '1:24:17',
    verified: true,
    subscribers: '1.2M',
    description: 'In this comprehensive tutorial, we build a complete full-stack application from scratch.',
    tags: ['nextjs', 'typescript', 'react'],
    likes: '87K',
  },
  {
    id: '2',
    title: 'Lofi Hip Hop Radio 🎵 – Beats to Relax / Study To',
    channel: 'ChillBeats',
    channelAvatar: 'https://i.pravatar.cc/40?img=2',
    thumbnail: 'https://picsum.photos/seed/lofi2/640/360',
    views: '14M',
    uploadedAt: '2 years ago',
    duration: 'LIVE',
    verified: true,
    subscribers: '5.4M',
    likes: '412K',
  },
  {
    id: '3',
    title: 'I Spent 30 Days Hiking the Entire Appalachian Trail Alone',
    channel: 'WildExplorer',
    channelAvatar: 'https://i.pravatar.cc/40?img=3',
    thumbnail: 'https://picsum.photos/seed/hike3/640/360',
    views: '8.1M',
    uploadedAt: '5 months ago',
    duration: '22:43',
    verified: false,
    subscribers: '890K',
    likes: '234K',
  },
  {
    id: '4',
    title: 'The Science Behind Why We Dream – Sleep Explained',
    channel: 'ScienceDaily',
    channelAvatar: 'https://i.pravatar.cc/40?img=4',
    thumbnail: 'https://picsum.photos/seed/science4/640/360',
    views: '3.7M',
    uploadedAt: '1 year ago',
    duration: '18:09',
    verified: true,
    subscribers: '3.1M',
    likes: '156K',
  },
  {
    id: '5',
    title: 'Gordon Ramsay Makes the Perfect Pasta Carbonara at Home',
    channel: 'GordonRamsay',
    channelAvatar: 'https://i.pravatar.cc/40?img=5',
    thumbnail: 'https://picsum.photos/seed/food5/640/360',
    views: '21M',
    uploadedAt: '8 months ago',
    duration: '9:32',
    verified: true,
    subscribers: '19.8M',
    likes: '623K',
  },
  {
    id: '6',
    title: 'UFC 300 Full Card Highlights – Best Knockouts & Submissions',
    channel: 'UFC Official',
    channelAvatar: 'https://i.pravatar.cc/40?img=6',
    thumbnail: 'https://picsum.photos/seed/ufc6/640/360',
    views: '45M',
    uploadedAt: '2 months ago',
    duration: '14:55',
    verified: true,
    subscribers: '12.3M',
    likes: '890K',
  },
  {
    id: '7',
    title: 'I Built a PC for $300 – Is It Worth It in 2025?',
    channel: 'TechTinkerer',
    channelAvatar: 'https://i.pravatar.cc/40?img=7',
    thumbnail: 'https://picsum.photos/seed/tech7/640/360',
    views: '1.9M',
    uploadedAt: '6 weeks ago',
    duration: '16:28',
    verified: false,
    subscribers: '650K',
    likes: '72K',
  },
  {
    id: '8',
    title: 'Every Country I Visited in 2024 – 40 Countries in 12 Months',
    channel: 'NomadVibes',
    channelAvatar: 'https://i.pravatar.cc/40?img=8',
    thumbnail: 'https://picsum.photos/seed/travel8/640/360',
    views: '5.2M',
    uploadedAt: '4 months ago',
    duration: '31:14',
    verified: true,
    subscribers: '2.7M',
    likes: '198K',
  },
  {
    id: '9',
    title: 'Minecraft But Every 60 Seconds the World Shrinks…',
    channel: 'PixelCraft',
    channelAvatar: 'https://i.pravatar.cc/40?img=9',
    thumbnail: 'https://picsum.photos/seed/game9/640/360',
    views: '12.4M',
    uploadedAt: '3 months ago',
    duration: '24:01',
    verified: true,
    subscribers: '8.9M',
    likes: '445K',
  },
  {
    id: '10',
    title: 'Taylor Swift – Eras Tour Full Concert 4K (Official)',
    channel: 'TaylorSwiftVEVO',
    channelAvatar: 'https://i.pravatar.cc/40?img=10',
    thumbnail: 'https://picsum.photos/seed/music10/640/360',
    views: '78M',
    uploadedAt: '1 year ago',
    duration: '3:12:44',
    verified: true,
    subscribers: '45.2M',
    likes: '2.1M',
  },
  {
    id: '11',
    title: 'I Tried to Learn Piano in 30 Days – Here\'s What Happened',
    channel: 'SkillQuest',
    channelAvatar: 'https://i.pravatar.cc/40?img=11',
    thumbnail: 'https://picsum.photos/seed/piano11/640/360',
    views: '4.6M',
    uploadedAt: '7 months ago',
    duration: '20:37',
    verified: false,
    subscribers: '1.1M',
    likes: '167K',
  },
  {
    id: '12',
    title: 'The Truth About AI Art – Is Human Creativity Dead?',
    channel: 'FutureTalks',
    channelAvatar: 'https://i.pravatar.cc/40?img=12',
    thumbnail: 'https://picsum.photos/seed/ai12/640/360',
    views: '6.8M',
    uploadedAt: '5 months ago',
    duration: '28:52',
    verified: true,
    subscribers: '4.3M',
    likes: '312K',
  },
  {
    id: '13',
    title: 'Morning Yoga for Beginners – 20 Minute Full Body Flow',
    channel: 'YogaWithAria',
    channelAvatar: 'https://i.pravatar.cc/40?img=13',
    thumbnail: 'https://picsum.photos/seed/yoga13/640/360',
    views: '9.3M',
    uploadedAt: '2 years ago',
    duration: '20:00',
    verified: true,
    subscribers: '6.7M',
    likes: '378K',
  },
  {
    id: '14',
    title: 'Why the Roman Empire Really Fell – Historians React',
    channel: 'HistoryUnlocked',
    channelAvatar: 'https://i.pravatar.cc/40?img=14',
    thumbnail: 'https://picsum.photos/seed/hist14/640/360',
    views: '3.2M',
    uploadedAt: '10 months ago',
    duration: '42:19',
    verified: true,
    subscribers: '2.2M',
    likes: '143K',
  },
  {
    id: '15',
    title: 'Cyberpunk 2077 – All Endings Explained (2025 Phantom Liberty)',
    channel: 'GameLore',
    channelAvatar: 'https://i.pravatar.cc/40?img=15',
    thumbnail: 'https://picsum.photos/seed/cp15/640/360',
    views: '7.5M',
    uploadedAt: '4 months ago',
    duration: '55:30',
    verified: false,
    subscribers: '3.5M',
    likes: '289K',
  },
  {
    id: '16',
    title: 'Street Food Tokyo – $5 Budget Challenge in Shibuya',
    channel: 'FoodGlobetrotter',
    channelAvatar: 'https://i.pravatar.cc/40?img=16',
    thumbnail: 'https://picsum.photos/seed/tokyo16/640/360',
    views: '11.2M',
    uploadedAt: '6 months ago',
    duration: '12:48',
    verified: true,
    subscribers: '7.8M',
    likes: '524K',
  },
];

export const SIDEBAR_NAV = [
  { icon: 'Home', label: 'Home', href: '/' },
  { icon: 'Compass', label: 'Explore', href: '/explore' },
  { icon: 'PlaySquare', label: 'Shorts', href: '/shorts' },
  { icon: 'Radio', label: 'Subscriptions', href: '/subscriptions' },
];

export const SIDEBAR_LIBRARY = [
  { icon: 'History', label: 'History', href: '/history' },
  { icon: 'ListVideo', label: 'Playlists', href: '/playlists' },
  { icon: 'Video', label: 'Your videos', href: '/your-videos' },
  { icon: 'Clock', label: 'Watch later', href: '/watch-later' },
  { icon: 'ThumbsUp', label: 'Liked videos', href: '/liked' },
];

export const SUBSCRIPTIONS = [
  { name: 'CodeWithMe', avatar: 'https://i.pravatar.cc/40?img=1', live: false },
  { name: 'ChillBeats', avatar: 'https://i.pravatar.cc/40?img=2', live: true },
  { name: 'WildExplorer', avatar: 'https://i.pravatar.cc/40?img=3', live: false },
  { name: 'ScienceDaily', avatar: 'https://i.pravatar.cc/40?img=4', live: false },
  { name: 'GordonRamsay', avatar: 'https://i.pravatar.cc/40?img=5', live: true },
  { name: 'TechTinkerer', avatar: 'https://i.pravatar.cc/40?img=7', live: false },
];
